import 10

type A = 10

public struct Point2D {
	public x: f32
	public y: f32
}

implement for Point2D {

	pub fn new(x: f32, y: f32) -> Point2D {
		return Point2D { x: x, y: y };
	}

	public fn length2(self) -> f32 {
		math.sqrt(self.length2())
	}
	
	public fn length2(self) -> f32 {
		self.x * self.x + self.y * self.y
	}

}

public fn pow(x: f32, m: u32) -> f32 = {
	var output = x
	var i = m

	until m == 0 {
		output *= x
		m -= 1
	}

	output
}

fn main() {
}
